name: Lint check

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: nightly
          components: rustfmt

      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3

      - run: pnpm i
      - run: pnpm run lint
